FROM neomediatech/ubuntu-base:20.04

ENV APP_VERSION=1.0.1 \
    SERVICE=dnsbl-ipset

LABEL maintainer="docker-dario@neomediatech.it" \
      org.label-schema.version=$APP_VERSION \
      org.label-schema.vcs-type=Git \
      org.label-schema.vcs-url=https://github.com/Neomediatech/$SERVICE \
      org.label-schema.maintainer=Neomediatech

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends \
      iptables ipset adns-tools rsyslog iproute2 whois && \
    rm -rf /var/lib/apt/lists*

RUN mkdir -p /etc/firehol

# this part is not working because you have to put it in the host
#    touch /var/log/iptables.log && \
#    echo ':msg, contains, "AUDIT IN=" /var/log/iptables.log' > /etc/rsyslog.d/00-iptables-audit.conf && \
#    echo '& stop' >> /etc/rsyslog.d/00-iptables-audit.conf && \
#    # disable imklog as reading /proc/kmsg is forbidden (and we don't need it)
#    sed -i 's/module(load="imklog" permitnonkernelfacility="on")/#module(load="imklog" permitnonkernelfacility="on")/' /etc/rsyslog.conf

COPY entrypoint.sh dnsbl-ipset.sh /
COPY dnsbl-ipset.conf /etc/firehol
RUN chmod +x /entrypoint.sh /dnsbl-ipset.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/dnsbl-ipset.sh"]

